version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices-network

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - mysql
    networks:
      - microservices-network

  student-service:
    build: ./student-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/student_db
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - eureka-server
    networks:
      - microservices-network

  enquiry-service:
    build: ./enquiry-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/enquiry_db
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - eureka-server
    networks:
      - microservices-network

  payment-service:
    build: ./payment-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/payment_db
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - eureka-server
    networks:
      - microservices-network

  staff-service:
    build: ./staff-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/staff_db
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - eureka-server
    networks:
      - microservices-network

  contact-service:
    build: ./contact-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/contact_db
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - eureka-server
    networks:
      - microservices-network

  auth-service:
    build: ./auth-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/auth_db
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - eureka-server
    networks:
      - microservices-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - student-service
      - enquiry-service
      - payment-service
      - staff-service
      - contact-service
      - auth-service
    networks:
      - microservices-network

volumes:
  mysql_data:

networks:
  microservices-network:
    driver: bridge
